global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.default.svc.cluster.local:8080']